# Generated by Django 4.0.2 on 2022-07-23 02:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.IntegerField(choices=[(1, 'DF'), (2, 'DR'), (3, 'DE'), (4, 'NE')], null=True, verbose_name=' Program Type')),
                ('name', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid Y-Group', regex='^[Y]-[A-Z0-9]{5}-[A-Z]{2}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_code', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WbsElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group_wbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_elements', to='core.groupwbs')),
            ],
        ),
        migrations.CreateModel(
            name='WbsElementUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_element_users', to=settings.AUTH_USER_MODEL)),
                ('wbs_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_element_users', to='core.wbselement')),
            ],
        ),
        migrations.AddField(
            model_name='wbselement',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='wbs_elements', through='core.WbsElementUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProgramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_users', to='core.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='programs', through='core.ProgramUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MaterialMasterUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='material_master_reports/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_master_uploads', to='core.program')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nomenclature', models.CharField(blank=True, max_length=100, null=True)),
                ('plant', models.CharField(max_length=100)),
                ('material_type', models.IntegerField(choices=[(3, 'MAKE'), (4, 'MSUB'), (5, 'PRCH')], null=True, verbose_name='Matl Type')),
                ('base_unit_of_measure', models.CharField(max_length=100)),
                ('procurement_type', models.CharField(max_length=100)),
                ('goods_receipt_time', models.IntegerField(blank=True, null=True)),
                ('planned_delivery_time', models.IntegerField(blank=True, null=True)),
                ('storage_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('base_drawing', models.CharField(blank=True, max_length=100, null=True)),
                ('electrical_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_master_items', to='core.materialmasterupload')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='inventory_reports/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_uploads', to='core.program')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=100)),
                ('storage_location', models.CharField(max_length=100)),
                ('material_type', models.IntegerField(choices=[(3, 'MAKE'), (4, 'MSUB'), (5, 'PRCH')], null=True, verbose_name='Matl Type')),
                ('wbs', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.CharField(max_length=100)),
                ('lot_date_code', models.CharField(blank=True, max_length=100, null=True)),
                ('base_unit_of_measure', models.CharField(max_length=100)),
                ('unrestricted_inventory', models.FloatField(null=True)),
                ('qm_lot_inventory', models.FloatField(null=True)),
                ('restricted_inventory', models.FloatField(null=True)),
                ('blocked_inventory', models.FloatField(null=True)),
                ('shelf_life_expiration_date', models.DateField(blank=True, null=True)),
                ('discard_date', models.DateField(blank=True, null=True)),
                ('on_hand_inventory', models.FloatField(null=True)),
                ('material_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='core.materialmaster', to_field='name')),
                ('program_group_wbs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.groupwbs')),
                ('upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.inventoryupload')),
            ],
        ),
        migrations.AddField(
            model_name='groupwbs',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_wbs_set', to='core.program'),
        ),
        migrations.CreateModel(
            name='ConfigurationItemUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(blank=True, null=True, upload_to='program_reports/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_item_uploads', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('configuration_type', models.IntegerField(choices=[(3, 'MAKE'), (4, 'MSUB'), (5, 'PRCH')], null=True, verbose_name='Item Type')),
                ('nomenclature', models.CharField(blank=True, max_length=100, null=True)),
                ('req_qty', models.FloatField(null=True)),
                ('req_date', models.DateField(blank=True, null=True)),
                ('net_order', models.CharField(max_length=100)),
                ('replenishment', models.CharField(max_length=100)),
                ('po_delivery', models.DateField(blank=True, null=True)),
                ('parents', models.ManyToManyField(related_name='children', to='core.ConfigurationItem')),
                ('upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_items', to='core.configurationitemupload')),
                ('wbs_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_items', to='core.wbselement')),
            ],
        ),
        migrations.CreateModel(
            name='AltSubUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='altsub_reports/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altsub_uploads', to='core.program')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AltSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=100)),
                ('type_code', models.CharField(max_length=100)),
                ('next_higher_assembly', models.CharField(blank=True, max_length=100, null=True)),
                ('alternate_or_substitute_code', models.CharField(max_length=100)),
                ('sub_code', models.CharField(max_length=100)),
                ('wbs_element', models.CharField(blank=True, max_length=100, null=True)),
                ('revision_level', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_for_change', models.CharField(blank=True, max_length=100, null=True)),
                ('item_text_line', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_altsubs', to='core.program')),
                ('primary_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_altsub_items', to='core.materialmaster', to_field='name')),
                ('replacement_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_altsub_items', to='core.materialmaster', to_field='name')),
                ('upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altsub_items', to='core.altsubupload')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wbselement',
            constraint=models.UniqueConstraint(fields=('group_wbs', 'name'), name='unique_wbs_elements'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_programs'),
        ),
        migrations.AddConstraint(
            model_name='groupwbs',
            constraint=models.UniqueConstraint(fields=('program', 'program_type'), name='unique_group_wbs'),
        ),
        migrations.AddConstraint(
            model_name='configurationitem',
            constraint=models.UniqueConstraint(fields=('wbs_element', 'name', 'configuration_type', 'net_order', 'replenishment'), name='unique_configuration_item'),
        ),
    ]
